string1 = 'CAGAATAGCATACGTGTTCTTTGAACGGGACCTGTAGCATGTGAACAACGTTTGTCGGCGGATATAATAGTTTAGCAAGTAAACTGTGTTTCGCAACTATTGCTGTATGGAGTGGTCAGGAACTCATTGTTACACGCCAGTTAGTAAGTTTCAACTCCGAAGCCGGAGTTGTCAAGGTTTCACAGGGGGTTAGCAATATTTATCGGCTCTTAGCGGTTACTACTCGGAGAACGGATACACACATAACACTTCATGCTGTGGAAAGTTAGTATTTCACAAATATATCCACCGAATAACGGATACACCCGGCTTATAGTGGCGTACGGACTCCAATTCATATGCCAGCATAAAGAGCGGCGTACGAATACGGGTCCCGTGCGAAGATCATGATGTGCCTATTGCAAGGAAACCTTCTCCATGGAAATGTGTGTTAGTTAGAGAGCACGCAGTCGACCAGACTTCGTCATAGGCGGGTCTAGTTAAATGGACCCGATTAATGAGTGGCAGGCTTTACTAATTGCGTCCGACCACAAGCATTCAAGTACCATTGCCGACCCTTGTTATAAGCTTCAATCTGTTACGCAGGTAACGTGTACATGGGGGCTGACTCCTCGTTCGGTTGCTATCCCCAGTACGAGGACGCTAGCGCTATTGCCGATCAGTCGTAGGCAATTCCGCTATTACTTCACCCTCCGCGTGCCACCGTGATCTGCGCTCACGTACGAGACGATAACGATCCCGGGCTATGCTGCCCTCGAATTTAGGTGGTTTAAGGTCTTATGATCGAACCAAAATCCGTCTACACGCTCTAACTGTTCGAGCCCACGCAAGATGTACGAAGGAAAGAGGATGTCCGCTGCACAGTTCTCTAAAGTCCGCCGGACAGTTTAAGCTACACCTCCGCAATC'
string2 = 'GAATGGAGGCTGGGGGCGACACTATATAATAACCAGGTGGGGTTTTGGGTATGATCAAGTGGCGTAAA'

def findMotif(string1, string2):
    result = ''
    offset = 0
    for char in string2:
        found = string1.find(char)
        
        result = result + str(found + 1 + offset)  + " "
        
        offset = offset + found + 1
        string1 = string1[found + 1:]
    return result

print(findMotif(string1, string2))